# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import terms_pb2 as terms__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in terms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TermsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/glossary.v1.TermsService/Health',
                request_serializer=terms__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=terms__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ListTerms = channel.unary_unary(
                '/glossary.v1.TermsService/ListTerms',
                request_serializer=terms__pb2.ListTermsRequest.SerializeToString,
                response_deserializer=terms__pb2.ListTermsResponse.FromString,
                _registered_method=True)
        self.GetTerm = channel.unary_unary(
                '/glossary.v1.TermsService/GetTerm',
                request_serializer=terms__pb2.GetTermRequest.SerializeToString,
                response_deserializer=terms__pb2.Term.FromString,
                _registered_method=True)
        self.CreateTerm = channel.unary_unary(
                '/glossary.v1.TermsService/CreateTerm',
                request_serializer=terms__pb2.CreateTermRequest.SerializeToString,
                response_deserializer=terms__pb2.Term.FromString,
                _registered_method=True)
        self.UpdateTerm = channel.unary_unary(
                '/glossary.v1.TermsService/UpdateTerm',
                request_serializer=terms__pb2.UpdateTermRequest.SerializeToString,
                response_deserializer=terms__pb2.Term.FromString,
                _registered_method=True)
        self.DeleteTerm = channel.unary_unary(
                '/glossary.v1.TermsService/DeleteTerm',
                request_serializer=terms__pb2.DeleteTermRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class TermsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTerms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TermsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=terms__pb2.HealthCheckRequest.FromString,
                    response_serializer=terms__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ListTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTerms,
                    request_deserializer=terms__pb2.ListTermsRequest.FromString,
                    response_serializer=terms__pb2.ListTermsResponse.SerializeToString,
            ),
            'GetTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTerm,
                    request_deserializer=terms__pb2.GetTermRequest.FromString,
                    response_serializer=terms__pb2.Term.SerializeToString,
            ),
            'CreateTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTerm,
                    request_deserializer=terms__pb2.CreateTermRequest.FromString,
                    response_serializer=terms__pb2.Term.SerializeToString,
            ),
            'UpdateTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTerm,
                    request_deserializer=terms__pb2.UpdateTermRequest.FromString,
                    response_serializer=terms__pb2.Term.SerializeToString,
            ),
            'DeleteTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTerm,
                    request_deserializer=terms__pb2.DeleteTermRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'glossary.v1.TermsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('glossary.v1.TermsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TermsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.v1.TermsService/Health',
            terms__pb2.HealthCheckRequest.SerializeToString,
            terms__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.v1.TermsService/ListTerms',
            terms__pb2.ListTermsRequest.SerializeToString,
            terms__pb2.ListTermsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.v1.TermsService/GetTerm',
            terms__pb2.GetTermRequest.SerializeToString,
            terms__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.v1.TermsService/CreateTerm',
            terms__pb2.CreateTermRequest.SerializeToString,
            terms__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.v1.TermsService/UpdateTerm',
            terms__pb2.UpdateTermRequest.SerializeToString,
            terms__pb2.Term.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.v1.TermsService/DeleteTerm',
            terms__pb2.DeleteTermRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
