# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: terms.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'terms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from .google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bterms.proto\x12\x0bglossary.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/api/annotations.proto\"8\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x12\n\x10ListTermsRequest\"5\n\x11ListTermsResponse\x12 \n\x05terms\x18\x01 \x03(\x0b\x32\x11.glossary.v1.Term\"!\n\x0eGetTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"9\n\x11\x43reateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x8a\x01\n\x11UpdateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x31\n\x0bnew_keyword\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x31\n\x0b\x64\x65scription\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"$\n\x11\x44\x65leteTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t2\xaf\x04\n\x0cTermsService\x12\\\n\x06Health\x12\x1f.glossary.v1.HealthCheckRequest\x1a .glossary.v1.HealthCheckResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\x07/health\x12Z\n\tListTerms\x12\x1d.glossary.v1.ListTermsRequest\x1a\x1e.glossary.v1.ListTermsResponse\"\x0e\x82\xd3\xe4\x93\x02\x08\x12\x06/terms\x12S\n\x07GetTerm\x12\x1b.glossary.v1.GetTermRequest\x1a\x11.glossary.v1.Term\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/terms/{keyword}\x12R\n\nCreateTerm\x12\x1e.glossary.v1.CreateTermRequest\x1a\x11.glossary.v1.Term\"\x11\x82\xd3\xe4\x93\x02\x0b\"\x06/terms:\x01*\x12\\\n\nUpdateTerm\x12\x1e.glossary.v1.UpdateTermRequest\x1a\x11.glossary.v1.Term\"\x1b\x82\xd3\xe4\x93\x02\x15\x1a\x10/terms/{keyword}:\x01*\x12^\n\nDeleteTerm\x12\x1e.glossary.v1.DeleteTermRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/terms/{keyword}B\x18Z\x16glossary/v1;glossaryv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'terms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026glossary/v1;glossaryv1'
  _globals['_TERMSSERVICE'].methods_by_name['Health']._loaded_options = None
  _globals['_TERMSSERVICE'].methods_by_name['Health']._serialized_options = b'\202\323\344\223\002\t\022\007/health'
  _globals['_TERMSSERVICE'].methods_by_name['ListTerms']._loaded_options = None
  _globals['_TERMSSERVICE'].methods_by_name['ListTerms']._serialized_options = b'\202\323\344\223\002\010\022\006/terms'
  _globals['_TERMSSERVICE'].methods_by_name['GetTerm']._loaded_options = None
  _globals['_TERMSSERVICE'].methods_by_name['GetTerm']._serialized_options = b'\202\323\344\223\002\022\022\020/terms/{keyword}'
  _globals['_TERMSSERVICE'].methods_by_name['CreateTerm']._loaded_options = None
  _globals['_TERMSSERVICE'].methods_by_name['CreateTerm']._serialized_options = b'\202\323\344\223\002\013\"\006/terms:\001*'
  _globals['_TERMSSERVICE'].methods_by_name['UpdateTerm']._loaded_options = None
  _globals['_TERMSSERVICE'].methods_by_name['UpdateTerm']._serialized_options = b'\202\323\344\223\002\025\032\020/terms/{keyword}:\001*'
  _globals['_TERMSSERVICE'].methods_by_name['DeleteTerm']._loaded_options = None
  _globals['_TERMSSERVICE'].methods_by_name['DeleteTerm']._serialized_options = b'\202\323\344\223\002\022*\020/terms/{keyword}'
  _globals['_TERM']._serialized_start=119
  _globals['_TERM']._serialized_end=175
  _globals['_HEALTHCHECKREQUEST']._serialized_start=177
  _globals['_HEALTHCHECKREQUEST']._serialized_end=197
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=199
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=236
  _globals['_LISTTERMSREQUEST']._serialized_start=238
  _globals['_LISTTERMSREQUEST']._serialized_end=256
  _globals['_LISTTERMSRESPONSE']._serialized_start=258
  _globals['_LISTTERMSRESPONSE']._serialized_end=311
  _globals['_GETTERMREQUEST']._serialized_start=313
  _globals['_GETTERMREQUEST']._serialized_end=346
  _globals['_CREATETERMREQUEST']._serialized_start=348
  _globals['_CREATETERMREQUEST']._serialized_end=405
  _globals['_UPDATETERMREQUEST']._serialized_start=408
  _globals['_UPDATETERMREQUEST']._serialized_end=546
  _globals['_DELETETERMREQUEST']._serialized_start=548
  _globals['_DELETETERMREQUEST']._serialized_end=584
  _globals['_TERMSSERVICE']._serialized_start=587
  _globals['_TERMSSERVICE']._serialized_end=1146
# @@protoc_insertion_point(module_scope)
